<?php

class Datos_recibo_model extends CI_Model {

    function __construct() {
        parent::__construct();
        $this->load->database();
    }
    public function get_dato_general($suministro,$periodo){
        $query = $this->db->query("select   ROWNUM,BARCOD, PORDESEXC,CLINOMBRE, CONREALMED, VOLFAC ,CLIELECT,".
                                  "CLIRUC ,PERIODO,CLICODFAX,DESCALLE,DESURBA,DESMES,FACEMIFEC,FECACT,FECANT,".
                              " FMEDIDOR,DESIMPORTE,CONSUMO,FSETIPCOD, TIPIMP , DESCRIREG ,OBSLEC, FACVENFEC,
                                CON01,CON02,CON03,CON04,CON05,CON06,CON07,CON08,CON09,CON10,CON11,CON12,CON13,".
                              "MES01,MES02,MES03,MES04,MES05,MES06,MES07,MES08,MES09,MES10,MES11,MES12,MES13,FACTOTAL,".
                              " FACSALDO,HORARIO,FGRUCOD,FGRUSUB,HORABS,FCICLO,DXSEM,PRECICFAC, LECACT,
                                LECANT,FACNRO,FACSERNRO,FACTARIFA,FACCHEDIG,CODCIM,
                                NUMERO,CARGARD,DESPREM,SUBTOT_ANT,ORDENRD,".
                             " DESFH ,MENSAJE2,MENSAJE,FACTOTSUB,FACIGV,REDONACT,REDONANT,".
                             " MENSCORTES,FACCICCOR,MENSCORTES,DESLOCAL FROM PRDDBFCOMERCIAL.REPFACIMP  WHERE CLICODFAX=".$suministro."AND PERIODO=".$periodo);
        return $query->result_array();
    }

    public function get_dato_general_mail($periodo,$token){
        $query = $this->db->query("select   ROWNUM,BARCOD, PORDESEXC,CLINOMBRE, CONREALMED, VOLFAC ,CLIELECT,".
                                  "CLIRUC ,PERIODO,CLICODFAX,DESCALLE,DESURBA,DESMES,FACEMIFEC,FECACT,FECANT,".
                              " FMEDIDOR,DESIMPORTE,CONSUMO,FSETIPCOD, TIPIMP , DESCRIREG ,OBSLEC, FACVENFEC,
                                CON01,CON02,CON03,CON04,CON05,CON06,CON07,CON08,CON09,CON10,CON11,CON12,CON13,".
                              "MES01,MES02,MES03,MES04,MES05,MES06,MES07,MES08,MES09,MES10,MES11,MES12,MES13,FACTOTAL,RECTOKEN,".
                              " FACSALDO,HORARIO,FGRUCOD,FGRUSUB,HORABS,FCICLO,DXSEM,PRECICFAC, LECACT,
                                LECANT,FACNRO,FACSERNRO,FACTARIFA,FACCHEDIG,CODCIM,
                                NUMERO,CARGARD,DESPREM,SUBTOT_ANT,ORDENRD,".
                             " DESFH ,MENSAJE2,MENSAJE,FACTOTSUB,FACIGV,REDONACT,REDONANT,".
                             " MENSCORTES,FACCICCOR,MENSCORTES,DESLOCAL FROM PRDDBFCOMERCIAL.REPFACIMP  WHERE RECTOKEN = '". $token . "' AND PERIODO =".$periodo);
        return $query->result_array();
    }
    
    public function get_dato_detalle($numero_recibo,$serie_recibo){
    $query = $this->db->query("select FACLINRO,DESCONCEP,IMPPRIRANG,IMPSEGRANG,IMPTERRANG,FACPRECI,REPFACIMP_FACNRO,REPFACIMP_FACSERNRO FROM PRDDBFCOMERCIAL.REPLINIMP WHERE REPFACIMP_FACNRO=".$numero_recibo.
			                 " AND REPFACIMP_FACSERNRO= ".$serie_recibo);
        return $query->result_array();
    }

    public function get_dato_fechas($suministro){
     $query = $this->db->query("select  ROWNUM,CLINOMBRE,CLICODFAX,DESMES,PERIODO".
                               " FROM PRDDBFCOMERCIAL.REPFACIMP  WHERE CLICODFAX=".$suministro);
        return $query->result_array();   
    }

    public function get_recibo_rango($ciclo, $periodo){
      $query = $this->db->query("SELECT COUNT(FCICLO) AS CANTIDAD FROM PRDDBFCOMERCIAL.REPFACIMP WHERE PERIODO = ".$periodo." AND FCICLO =".$ciclo);
      return $query->result_array();
  }
  public function get_rangos($periodo, $ciclo, $rango){
    
    $query = $this->db->query("select PORDESEXC,CLINOMBRE, CONREALMED, VOLFAC ,CLIELECT,
    CLIRUC ,PERIODO,CLICODFAX,DESCALLE,DESURBA,DESMES,FACEMIFEC,FECACT,FECANT,
    FMEDIDOR,DESIMPORTE,CONSUMO,FSETIPCOD, TIPIMP , DESCRIREG ,OBSLEC, FACVENFEC,
    FACTOTAL, FACSALDO,HORARIO,FGRUSUB,HORABS,FCICLO,DXSEM,PRECICFAC, LECACT,LECANT,FACNRO,
    FACSERNRO,FACTARIFA,FACCHEDIG,CODCIM,NUMERO,CARGARD,DESPREM,SUBTOT_ANT,FGRUCOD,ORDENRD,DESFH ,
    MENSAJE2,MENSAJE,FACTOTSUB,FACIGV,REDONACT,REDONANT,MENSCORTES,FACCICCOR,DESLOCAL
    from ( select /*+ FIRST_ROWS(n) */ 
    a.*, ROWNUM rnum 
        from  PRDDBFCOMERCIAL.REPFACIMP  a 
        where  FCICLO=".$ciclo." AND PERIODO = ".$periodo." AND  ROWNUM <= ".$rango[1]." ) 
    where rnum  >= ".$rango[0]);
  return $query->result_array();
  }
  public function get_rangos2($periodo, $ciclo, $rango){
    
      $query = $this->db->query(" SELECT DETALLE.FACLINRO,DETALLE.DESCONCEP,DETALLE.IMPPRIRANG,DETALLE.IMPSEGRANG,DETALLE.IMPTERRANG,
      DETALLE.FACPRECI,DETALLE.REPFACIMP_FACNRO,DETALLE.REPFACIMP_FACSERNRO,CABECERA.PORDESEXC,CABECERA.CLINOMBRE, CABECERA.CONREALMED, CABECERA.VOLFAC ,CABECERA.CLIELECT,
      CABECERA.CLIRUC ,CABECERA.PERIODO,CABECERA.CLICODFAX,CABECERA.DESCALLE,CABECERA.DESURBA,CABECERA.DESMES,CABECERA.FACEMIFEC,CABECERA.FECACT,CABECERA.FECANT,
      CABECERA.FMEDIDOR,CABECERA.DESIMPORTE,CABECERA.CONSUMO,CABECERA.FSETIPCOD, CABECERA.TIPIMP , CABECERA.DESCRIREG ,CABECERA.OBSLEC, CABECERA.FACVENFEC,
      CABECERA.FACTOTAL, CABECERA.FACSALDO,CABECERA.HORARIO,CABECERA.FGRUSUB,CABECERA.HORABS,CABECERA.FCICLO,CABECERA.DXSEM,CABECERA.PRECICFAC, CABECERA.LECACT,CABECERA.LECANT,CABECERA.FACNRO,
      CABECERA.FACSERNRO,CABECERA.FACTARIFA,CABECERA.FACCHEDIG,CABECERA.CODCIM,CABECERA.NUMERO,CABECERA.CARGARD,CABECERA.DESPREM,CABECERA.SUBTOT_ANT,CABECERA.FGRUCOD,CABECERA.ORDENRD,CABECERA.DESFH,
      CABECERA.MENSAJE2,CABECERA.MENSAJE,  CABECERA.FACTOTSUB ,CABECERA.FACIGV , CABECERA.REDONACT, CABECERA.REDONANT, CABECERA.MENSCORTES, CABECERA.FACCICCOR,  CABECERA.DESLOCAL, 
      CABECERA.CON01,CABECERA.CON02,CABECERA.CON03,CABECERA.CON04,CABECERA.CON05,CABECERA.CON06,CABECERA.CON07,CABECERA.CON08,CABECERA.CON09,CABECERA.CON10,CABECERA.CON11,CABECERA.CON12,CABECERA.CON13,
      CABECERA.MES01,CABECERA.MES02,CABECERA.MES03,CABECERA.MES04,CABECERA.MES05,CABECERA.MES06,CABECERA.MES07,CABECERA.MES08,CABECERA.MES09,CABECERA.MES10,CABECERA.MES11,CABECERA.MES12,CABECERA.MES13 FROM PRDDBFCOMERCIAL.REPLINIMP  DETALLE, (select 
      PORDESEXC,CLINOMBRE, CONREALMED, VOLFAC ,CLIELECT,
      CLIRUC ,PERIODO,CLICODFAX,DESCALLE,DESURBA,DESMES,FACEMIFEC,FECACT,FECANT,
      FMEDIDOR,DESIMPORTE,CONSUMO,FSETIPCOD, TIPIMP , DESCRIREG ,OBSLEC, FACVENFEC,
      FACTOTAL, FACSALDO,HORARIO,FGRUSUB,HORABS,FCICLO,DXSEM,PRECICFAC, LECACT,LECANT,FACNRO,
      FACSERNRO,FACTARIFA,FACCHEDIG,CODCIM,NUMERO,CARGARD,DESPREM,SUBTOT_ANT,FGRUCOD,ORDENRD,DESFH ,
      MENSAJE2,MENSAJE,FACTOTSUB,FACIGV,REDONACT,REDONANT,MENSCORTES,FACCICCOR,DESLOCAL,CON01,CON02,CON03,CON04,CON05,CON06,CON07,CON08,CON09,CON10,CON11,CON12,CON13,
      MES01,MES02,MES03,MES04,MES05,MES06,MES07,MES08,MES09,MES10,MES11,MES12,MES13
      from ( select /*+ FIRST_ROWS(n) */ 
      a.*, ROWNUM rnum 
          from  PRDDBFCOMERCIAL.REPFACIMP  a 
          where FCICLO=".$ciclo." AND PERIODO = ".$periodo." AND  ROWNUM <= ".$rango[1]." )
      where rnum  >= ".$rango[0].") CABECERA  WHERE DETALLE.REPFACIMP_FACSERNRO = CABECERA.FACSERNRO AND DETALLE.REPFACIMP_FACNRO = CABECERA.FACNRO");
    return $query->result_array();
    }
  public function get_recibo_ser_nro($serie,$numero){
      $query = $this->db->query("select PORDESEXC,CLINOMBRE, CONREALMED, VOLFAC ,CLIELECT,
    CLIRUC ,PERIODO,CLICODFAX,DESCALLE,DESURBA,DESMES,FACEMIFEC,FECACT,FECANT,
    FMEDIDOR,DESIMPORTE,CONSUMO,FSETIPCOD, TIPIMP , DESCRIREG ,OBSLEC, FACVENFEC,TRIM(BARCOD) AS CODIGO_BARRA,
    FACTOTAL, FACSALDO,HORARIO,FGRUSUB,HORABS,FCICLO,DXSEM,PRECICFAC, LECACT,LECANT,FACNRO,
    FACSERNRO,FACTARIFA,FACCHEDIG,CODCIM,NUMERO,CARGARD,DESPREM,SUBTOT_ANT,FGRUCOD,ORDENRD,DESFH ,
    MENSAJE2,MENSAJE,FACTOTSUB,FACIGV,REDONACT,REDONANT,MENSCORTES,FACCICCOR,MENSCORTES,DESLOCAL,CON01,CON02,CON03,CON04,CON05,CON06,CON07,CON08,CON09,CON10,CON11,CON12,CON13,
    MES01,MES02,MES03,MES04,MES05,MES06,MES07,MES08,MES09,MES10,MES11,MES12,MES13
    from PRDDBFCOMERCIAL.REPFACIMP WHERE FACNRO = ".$numero." AND FACSERNRO = ".$serie);
  return $query->result_array();
  }

  public function get_rango_recibo_unico($suministro, $periodo_inicio, $periodo_fin){
      $query = $this->db->query("SELECT CLINOMBRE,PERIODO,DESURBA,FACTOTAL, FACSALDO, DESCALLE, DESURBA,
                                   FACNRO, FACSERNRO, DESMES  FROM PRDDBFCOMERCIAL.REPFACIMP WHERE CLICODFAX=".$suministro." AND PERIODO >= ".$periodo_inicio." AND PERIODO <= ".$periodo_fin);
      return $query->result_array();
  }

  public function get_rango_suministro_unico($suministro, $periodo_inicio){
      $query = $this->db->query("SELECT CLINOMBRE,PERIODO,DESURBA,FACTOTAL, FACSALDO, DESCALLE, DESURBA,
                                   FACNRO, FACSERNRO, DESMES, CLINOMBRE, FACTARIFA  FROM PRDDBFCOMERCIAL.REPFACIMP WHERE CLICODFAX=".$suministro." AND PERIODO = ".$periodo_inicio);
      return $query->result_array();
  }

  public function get_rangos_imagenes($periodo, $ciclo, $rango){
      $query = $this->db->query("select TRIM(BARCOD) AS CODIGO_BARRA, CLICODFAX,FMEDIDOR
      from ( select /*+ FIRST_ROWS(n) */ 
      a.*, ROWNUM rnum 
          from  PRDDBFCOMERCIAL.REPFACIMP  a 
          where  FCICLO=".$ciclo." AND PERIODO = ".$periodo." AND  ROWNUM <= ".$rango[1]." ) 
      where rnum  >= ".$rango[0]);
      return $query->result_array();
  }

  public function get_recibo_rango_varios($ciclo, $periodo, $desde, $hasta ){
      $query = $this->db->query("select COUNT(FCICLO) AS CANTIDAD, MAX(CLICODFAX) AS MAXCODIGO, MIN(CLICODFAX) AS MINCODIGO
      from ( select /*+ FIRST_ROWS(n) */ 
      a.*, ROWNUM rnum 
          from  PRDDBFCOMERCIAL.REPFACIMP  a 
          where  FCICLO= ? AND PERIODO = ? AND  ROWNUM <= ? ) 
      where rnum  >= ?" , array($ciclo, $periodo, $hasta , $desde));
  return $query->result_array();
  }
}

?>