<?php 
    if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

    /**
    *   MODELO Agua_subterranea_model
    *   -------------------------------------------------
    *   Modelo creado para el reclamo de aguas subterraneas
    *   Creado: JALO (Jhon A. Leon Ortecho)
    *   Fecha: 22/03/2019
    *   
    */

    class Agua_subterranea_model extends CI_Model {
        function __construct() {
            parent::__construct();
            $this->load->database();
            $this->oracle = $this->load->database('oracle', TRUE);
        }

        public function getTipoDocumento(){
            $query = $this->oracle->query('SELECT * FROM PRDDBFCOMERCIAL.TIPDOC');
            return $query->result_array();
        }

        public function getPersona($tipo, $numero){
            if($tipo == 8){
                if(strlen($numero) == 7){
                    $grupo = substr($numero, 0, 3);
                    $subgrupo = substr($numero, 3, 4);
                    $query = $this->oracle->query("SELECT CLIENT.CLICODFAC, GR.CODGRUPO, GR.CLINOMBRE, TRIM(SUBSTR(LOCALI.LOCDES,6,60)) AS LOCALIDAD, GR.CLIAPELLPE, GR.CLIAPELLM, GR.CLINOMBR1, GR.CLINOMBR2,
                    TRIM(RLURBA.URBDES) AS URBANIZACION ,TRIM(RLCALL.CALDES) AS CALLE, PREDIO.PREMUNI AS NUMERO,  
                    GR.CLIELECT AS DNI, GR.CLIRUC AS RUC, GR.CONTRA AS CONTRATO, GR.TARIFA, GR.CODCATTAR, TARIFA.DESCATTAR AS CATEGTARIF, AMBITO.AMBDES, REGLOC.REGDES, PREDIO.PREREGION, 
                    PREDIO.PREZONA, PREDIO.PRESECTOR, PREDIO.PREMZN, PREDIO.PRELOTE, CLIENT.CLICODID, CLIENT.CLICODIGO, PREDIO.MANZANAOK, PREDIO.LOTEOK, 
                    PREDIO.SECCEN, PREDIO.MANZCEN, PREDIO.LOTECEN, PREDIO.PRELOCALI, LOCALI.LOCDES AS LOCALIDAD, PREDIO.PREURBA, RLURBA.URBDES AS URBANIZACION, PREDIO.PRECALLE, 
                    RLCALL.CALDES AS CALLE, PREDIO.PREMUNI AS NUMMUNICIPAL, PREDIO.FACCICCOD AS CICLO, PREDIO.PREFRONT AS FRONTERA, PREDIO.PREINMPIS AS NROPISOS, PREDIO.PRECLINRO AS NROCLIE, 
                    CLIENT.CLIPERSNO AS NROPERSON, PREDIO.CODESTPRE, ESTPRE.DESESTPRE AS ESTADOPREDIO, PREDIO.CODTIPINM, TIPINM.DESTIPINM AS TIPOINMUEBLE, PREDIO.CODTIPRES, 
                    RESEVO.DESTIPRES AS TIPOALMAC, PREDIO.CODMATCON, MATCON.DESMATCON AS MATCONSTRUC, PREDIO.PISCINCOD, PISCIN.PISCONDES AS PISCINA, PREDIO.CLLPAVCOD, TPAVIM.PAVDESC AS TIPOPAVIM, 
                    PREDIO.VDAMATCOD, MATVER.DESMATVER AS MATERVEREDA, PREDIO.PREREDAGU AS PASAAGUA, PREDIO.PREREDDES AS PASADESG, PREDIO.PRECONAGU AS NROCNXAG, 
                    PREDIO.PRECONDES AS NROCNXDSG, COAGUA.CONESTADO, ESTCON.CONESTDES AS ESTADOCONXAG, CLIENT.INMUSOCOD, USOINM.INMUSODES AS USOINMUEB, CLIENT.CLIGRUCOD AS GRUPO, 
                    CLIENT.CLIGRUSUB AS SUBGRUPO, CLIENT.CODSCATTA AS SUBCATEGORIA, CLIENT.CIRPROY AS CIRCUITPROY, CLIENT.CEMVOLCONA AS CLASE, CLIENT.FECCEN, CLIENT.CODESCLTE , ESCLTE.DESESCLTE AS ESTADOCLI, 
                    CLIENT.CODTIPSER, TIPSER.DESTIPSER AS TIPOSERVICIO, CLIENT.CODTIPTEN, TIPTEN.DESTIPTEN AS TIPOTENENCIA, CLIENT.CODABASAG, TABSAG.DESABASAG AS ABASTECAGUA, CLIENT.CODABASDE, 
                    TABSDE.DESABASDE AS ABASTECDSG, NVL(COAGUA.CONCAJA,0) AS CONCAJA, COAGUA.CONCODTIP, COAGUA.CONCODIGO, COAGUA.NIVPRES, COAGUA.CONDIACOD, DICOAG.CONDIADES AS DIAMCNXAGUA, 
                    COAGUA.CNAMATCOD, TMCXAG.CNAMATDES AS MATERCONXAGUA, COAGUA.AGUTABCOD, TBPCJA.AGUTABDES AS MATERTAPAAGUA, COAGUA.ESTTAPCOD, TBTPST.ESTTAPDES AS ESTADOTAPAGUA, COAGUA.CONUBICAJ, 
                    UBIMED.UBICAJDES AS UBICAJAAGUA, COAGUA.CONCAJMAT, MATCJA.CONCAJDES AS MATERCAJAAGUA, COAGUA.CAJESTCOD AS CODESTCAJAG, ESCJAG.CAJESTDES AS ESTCAJAG, COAGUA.CONENTEJX, EJECCNXAGUA.ENTEEJEAGUDES, 
                    COAGUA.CONCIRCUI, COAGUA.ACONTRATO, COAGUA.MEDCODIGO AS CORRMEDIDOR, MEDIDO.MEDCODYGO AS MEDIDOR, MEDIDO.MEDFECINS, MEDIDO.DIAMEDCOD, 
                    TRIM(DICOAGMED.DIAMEDDES) || ' \"' AS DIAMEDIDOR,
                    MEDIDO.MEDESTCOD, ESMEDI.MESESTDES, MEDIDO.MEDTIPCODX, TIPMED.MEDTIPDES, MEDIDO.MEDMARCODX, 
                    TMARMED.MAMDES, MEDIDO.MEDMODCODX, TMARMEDLEVEL1.MOMDES, MEDIDO.MEDFECFAC, MEDIDO.MEDFECRET, MEDIDO.MEDFECREG, MEDIDO.MEDLLACOD, 
                    MEDIDO.MEDCONCOD, TMEDCONDICION.MEDCONDES, NVL(CODESA.CONDCAJA,0) AS CONDCAJA, CODESA.CONDESTAD, ESTCONDE.CONDESDES, CODESA.CONDIDCOD, 
                    DICODE.CONDIDDES, CODESA.DCONTRATO, CODESA.CONCODTDE, CODESA.CONCODDES, CODESA.CONDENTEJX, CODESA.CAJESTCOD AS CODESTCAJDSG, ESCJAG.CAJESTDES AS ESTCAJDSG, 
                    CODESA.CAJMATCOD, MATCJADE.CAJMATDES, CODESA.CONDUBICA, UBIMEDDES.CONDUBIDES, CODESA.DESTAPCOD, TBPCJAD.DESTAPDES, 
                    CODESA.STDTAPCOD, TBTPSTDES.STDTAPDES, CLIENT.PORTARIFA, CLIENT.ORDENRL, CLIENT.CARGARL, GR.CARGARD, GR.ORDENRD, 
                    CODESA.DCONFECFIR, CODESA.CODFECING, ENTEJE.ENTEJEDES, PROVIN.PROVINDES, ZONASEC.ZONASECSRV, 
                    TO_CHAR(SYSDATE, 'DD/MM/YYYY') AS FECHAPROCESO, TO_CHAR(SYSDATE, 'HH24:MI:SS') AS HORAPROCESO 
                    FROM PRDCOMCATMEDLEC.PREDIO 
                    INNER JOIN PRDCOMCATMEDLEC.CLIENT ON (PREDIO.PREREGION = CLIENT.PREREGION) AND (PREDIO.PREZONA = CLIENT.PREZONA) AND (PREDIO.PRESECTOR = CLIENT.PRESECTOR) AND (PREDIO.PREMZN = CLIENT.PREMZN) AND (PREDIO.PRELOTE = CLIENT.PRELOTE) 
                    AND CLIENT.CLIGRUCOD =  ? AND CLIENT.CLIGRUSUB = ? 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.COAGUA ON (PREDIO.PREREGION = COAGUA.PREREGION) AND (PREDIO.PREZONA = COAGUA.PREZONA) AND (PREDIO.PRESECTOR = COAGUA.PRESECTOR) AND (PREDIO.PREMZN = COAGUA.PREMZN) AND (PREDIO.PRELOTE = COAGUA.PRELOTE) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ZONASEC ON (ZONASEC.PREREGION = PREDIO.PREREGION) AND (ZONASEC.PREZONA = PREDIO.PREZONA) AND (ZONASEC.PRESECTOR = PREDIO.PRESECTOR) AND (ZONASEC.PRELOCALI = PREDIO.PRELOCALI) 
                    INNER JOIN PRDCOMCATMEDLEC.RLURBA ON (RLURBA.PREREGION = PREDIO.PREREGION) AND (RLURBA.PRELOCALI = PREDIO.PRELOCALI) AND (RLURBA.PREURBA = PREDIO.PREURBA) 
                    INNER JOIN PRDCOMCATMEDLEC.RLCALL ON (RLCALL.PREREGION = PREDIO.PREREGION) AND (RLCALL.PRELOCALI = PREDIO.PRELOCALI) AND (RLCALL.PRECALLE = PREDIO.PRECALLE) 
                    INNER JOIN PRDCOMCATMEDLEC.LOCALI ON (LOCALI.PREREGION = PREDIO.PREREGION) AND (LOCALI.PRELOCALI = PREDIO.PRELOCALI) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.CODESA ON (PREDIO.PREREGION = CODESA.PREREGION) AND (PREDIO.PREZONA = CODESA.PREZONA) AND (PREDIO.PRESECTOR = CODESA.PRESECTOR) AND (PREDIO.PREMZN = CODESA.PREMZN) AND (PREDIO.PRELOTE = CODESA.PRELOTE) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESTPRE ON (ESTPRE.CODESTPRE = PREDIO.CODESTPRE) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MATCON ON (MATCON.CODMATCON = PREDIO.CODMATCON) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MATVER ON (CODMATVER = VDAMATCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.PISCIN ON (PISCIN.PISCINCOD = PREDIO.PISCINCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.PROVIN ON (PROVINCOD = PREPROVIN) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.RESEVO ON (RESEVO.CODTIPRES = PREDIO.CODTIPRES) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TIPINM ON (TIPINM.CODTIPINM = PREDIO.CODTIPINM) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TPAVIM ON (PAVICOD = CLLPAVCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ENTEJE ON (ENTEJE.CONDENTEJX = CODESA.CONDENTEJX) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESCJAG ON (ESCJAG.CAJESTCOD = CODESA.CAJESTCOD) AND (ESCJAG.CAJESTCOD = COAGUA.CAJESTCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MEDIDO ON (MEDIDO.MEDCODIGO = COAGUA.MEDCODIGO) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.DICOAGMED ON (DICOAGMED.DIAMEDCOD = MEDIDO.DIAMEDCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESMEDI ON (ESMEDI.MEDESTCOD = MEDIDO.MEDESTCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TIPMED ON (TIPMED.MEDTIPCODX = MEDIDO.MEDTIPCODX) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TMEDCONDICION ON (TMEDCONDICION.MEDCONCOD = MEDIDO.MEDCONCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MMEDIDORFAB ON (MMEDIDORFAB.MEDCODYGO = MEDIDO.MEDCODYGO) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TMARMED ON (TMARMED.MAMCOD = MMEDIDORFAB.MAMCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TMARMEDLEVEL1 ON (TMARMEDLEVEL1.MAMCOD = MMEDIDORFAB.MAMCOD) AND (TMARMEDLEVEL1.MOMCOD = MMEDIDORFAB.MOMCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.DICOAG ON (DICOAG.CONDIACOD = COAGUA.CONDIACOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.EJECCNXAGUA ON (EJECCNXAGUA.CONENTEJX = COAGUA.CONENTEJX) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESTCON ON (ESTCON.CONESTADO = COAGUA.CONESTADO) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MATCJA ON (MATCJA.CONCAJMAT = COAGUA.CONCAJMAT) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TBPCJA ON (TBPCJA.AGUTABCOD = COAGUA.AGUTABCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TBTPST ON (TBTPST.ESTTAPCOD = COAGUA.ESTTAPCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TMCXAG ON (TMCXAG.CNAMATCOD = COAGUA.CNAMATCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.UBIMED ON (UBIMED.CONUBICAJ = COAGUA.CONUBICAJ) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESTCONDE ON (ESTCONDE.CONDESTAD = CODESA.CONDESTAD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MATCJADE ON (MATCJADE.CAJMATCOD = CODESA.CAJMATCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TBPCJAD ON (TBPCJAD.DESTAPCOD = CODESA.DESTAPCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TBTPSTDES ON (TBTPSTDES.STDTAPCOD = CODESA.STDTAPCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.UBIMEDDES ON (UBIMEDDES.CONDUBICA = CODESA.CONDUBICA) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.DICODE ON (DICODE.CONDIDCOD = CODESA.CONDIDCOD) 
                    INNER JOIN (SELECT PROPIE.*, SUBSTR(TRIM(PROPIE.CLICODFAC),1,3) || SUBSTR(TRIM(PROPIE.CLICODFAC),8,4) AS CODGRUPO FROM PRDCOMCATMEDLEC.PROPIE WHERE  SUBSTR(TRIM(PROPIE.CLICODFAC),4,4) = '0000') GR ON GR.CLICODFAC =  TRIM(TO_CHAR(CLIENT.CLIGRUCOD,'000')) || '0000'|| TRIM(TO_CHAR(CLIENT.CLIGRUSUB,'0000')) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.REGLOC ON (REGLOC.PREREGION = GR.PREREGION) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TARIFA ON (TARIFA.CODCATTAR = GR.CODCATTAR) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESCLTE ON (ESCLTE.CODESCLTE = CLIENT.CODESCLTE) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TABSAG ON (TABSAG.CODABASAG = CLIENT.CODABASAG) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TABSDE ON (TABSDE.CODABASDE = CLIENT.CODABASDE) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TIPSER ON (TIPSER.CODTIPSER = CLIENT.CODTIPSER) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TIPTEN ON (TIPTEN.CODTIPTEN = CLIENT.CODTIPTEN) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.USOINM ON (USOINM.INMUSOCOD = CLIENT.INMUSOCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.AMBITO ON (AMBITO.AMBCOD = LOCALI.AMBCOD) 
                    WHERE ROWNUM = 1        
                    ORDER BY PREDIO.PREREGION, PREDIO.PREZONA, PREDIO.PRESECTOR, PREDIO.PREMZN, PREDIO.PRELOTE, CLIENT.CLICODID, CLIENT.CLICODIGO ", array($grupo, $subgrupo));
                } else {
                    $query = $this->oracle->query("SELECT CLIENT.CLICODFAC, TRIM(PROPIE.CLINOMBRE) AS NOMBRE, TRIM(SUBSTR(LOCALI.LOCDES,6,60)) AS LOCALIDAD,  PROPIE.CLIAPELLPE, PROPIE.CLIAPELLM, PROPIE.CLINOMBR1, PROPIE.CLINOMBR2,
                    TRIM(RLURBA.URBDES) AS URBANIZACION ,TRIM(RLCALL.CALDES) AS CALLE, PREDIO.PREMUNI AS NUMERO, 
                    NVL(PROPIE.CLIELECT,' ') AS DNI, NVL(PROPIE.CLIRUC,' ') AS RUC, PROPIE.CONTRA AS CONTRATO, PROPIE.TARIFA, PROPIE.CODCATTAR, TARIFA.DESCATTAR AS CATEGTARIF, REGLOC.REGDES, PREDIO.PREREGION, 
                    PREDIO.PREZONA, PREDIO.PRESECTOR, PREDIO.PREMZN, PREDIO.PRELOTE, LOCALI.AMBCOD, AMBITO.AMBDES, CLIENT.CLICODID, CLIENT.CLICODIGO, PREDIO.MANZANAOK, PREDIO.LOTEOK, 
                    PREDIO.SECCEN, PREDIO.MANZCEN, PREDIO.LOTECEN, PREDIO.PRELOCALI, LOCALI.LOCDES AS LOCALIDAD, PREDIO.PREURBA, RLURBA.URBDES AS URBANIZACION, PREDIO.PRECALLE, 
                    RLCALL.CALDES AS CALLE, PREDIO.PREMUNI AS NUMMUNICIPAL, PREDIO.FACCICCOD AS CICLO, PREDIO.PREFRONT AS FRONTERA, PREDIO.PREINMPIS AS NROPISOS, PREDIO.PRECLINRO AS NROCLIE, 
                    CLIENT.CLIPERSNO AS NROPERSON, PREDIO.CODESTPRE, ESTPRE.DESESTPRE AS ESTADOPREDIO, PREDIO.CODTIPINM, TIPINM.DESTIPINM AS TIPOINMUEBLE, PREDIO.CODTIPRES, 
                    RESEVO.DESTIPRES AS TIPOALMAC, PREDIO.CODMATCON, MATCON.DESMATCON AS MATCONSTRUC, PREDIO.PISCINCOD, PISCIN.PISCONDES AS PISCINA, PREDIO.CLLPAVCOD, TPAVIM.PAVDESC AS TIPOPAVIM, 
                    PREDIO.VDAMATCOD, MATVER.DESMATVER AS MATERVEREDA, PREDIO.PREREDAGU AS PASAAGUA, PREDIO.PREREDDES AS PASADESG, PREDIO.PRECONAGU AS NROCNXAG, 
                    PREDIO.PRECONDES AS NROCNXDSG, COAGUA.CONESTADO, ESTCON.CONESTDES AS ESTADOCONXAG, CLIENT.INMUSOCOD, USOINM.INMUSODES AS USOINMUEB, CLIENT.CLIGRUCOD AS GRUPO, 
                    CLIENT.CLIGRUSUB AS SUBGRUPO, CLIENT.CODSCATTA AS SUBCATEGORIA, CLIENT.CIRPROY AS CIRCUITPROY, CLIENT.CEMVOLCONA AS CLASE, CLIENT.FECCEN, CLIENT.CODESCLTE , ESCLTE.DESESCLTE AS ESTADOCLI, 
                    CLIENT.CODTIPSER, TIPSER.DESTIPSER AS TIPOSERVICIO, CLIENT.CODTIPTEN, TIPTEN.DESTIPTEN AS TIPOTENENCIA, CLIENT.CODABASAG, TABSAG.DESABASAG AS ABASTECAGUA, CLIENT.CODABASDE, 
                    TABSDE.DESABASDE AS ABASTECDSG, NVL(COAGUA.CONCAJA,0) AS CONCAJA, COAGUA.CONCODTIP, COAGUA.CONCODIGO, COAGUA.NIVPRES, COAGUA.CONDIACOD, DICOAG.CONDIADES AS DIAMCNXAGUA, 
                    COAGUA.CNAMATCOD, TMCXAG.CNAMATDES AS MATERCONXAGUA, COAGUA.AGUTABCOD, TBPCJA.AGUTABDES AS MATERTAPAAGUA, COAGUA.ESTTAPCOD, TBTPST.ESTTAPDES AS ESTADOTAPAGUA, COAGUA.CONUBICAJ, 
                    UBIMED.UBICAJDES AS UBICAJAAGUA, COAGUA.CONCAJMAT, MATCJA.CONCAJDES AS MATERCAJAAGUA, COAGUA.CAJESTCOD AS CODESTCAJAG, ESCJAG.CAJESTDES AS ESTCAJAG, COAGUA.CONENTEJX, EJECCNXAGUA.ENTEEJEAGUDES, 
                    COAGUA.CONCIRCUI, COAGUA.ACONTRATO, COAGUA.MEDCODIGO AS CORRMEDIDOR, MEDIDO.MEDCODYGO AS MEDIDOR, MEDIDO.MEDFECINS, MEDIDO.DIAMEDCOD, 
                    TRIM(DICOAGMED.DIAMEDDES) || ' \"' AS DIAMEDIDOR, 
                    MEDIDO.MEDESTCOD, ESMEDI.MESESTDES, MEDIDO.MEDTIPCODX, TIPMED.MEDTIPDES, MEDIDO.MEDMARCODX, 
                    TMARMED.MAMDES, MEDIDO.MEDMODCODX, TMARMEDLEVEL1.MOMDES, MEDIDO.MEDFECFAC, MEDIDO.MEDFECRET, MEDIDO.MEDFECREG, MEDIDO.MEDLLACOD, 
                    MEDIDO.MEDCONCOD, TMEDCONDICION.MEDCONDES, NVL(CODESA.CONDCAJA,0) AS CONDCAJA, CODESA.CONDESTAD, ESTCONDE.CONDESDES, CODESA.CONDIDCOD, 
                    DICODE.CONDIDDES, CODESA.DCONTRATO, CODESA.CONCODTDE, CODESA.CONCODDES, CODESA.CONDENTEJX, CODESA.CAJESTCOD AS CODESTCAJDSG, ESCJAG.CAJESTDES AS ESTCAJDSG, 
                    CODESA.CAJMATCOD, MATCJADE.CAJMATDES, CODESA.CONDUBICA, UBIMEDDES.CONDUBIDES, CODESA.DESTAPCOD, TBPCJAD.DESTAPDES, 
                    CODESA.STDTAPCOD, TBTPSTDES.STDTAPDES, CLIENT.PORTARIFA, CLIENT.ORDENRL, CLIENT.CARGARL, PROPIE.CARGARD, PROPIE.ORDENRD, 
                    CODESA.DCONFECFIR, CODESA.CODFECING, ENTEJE.ENTEJEDES, PROVIN.PROVINDES, ZONASEC.ZONASECSRV, 
                    TO_CHAR(SYSDATE, 'DD/MM/YYYY') AS FECHAPROCESO, TO_CHAR(SYSDATE, 'HH24:MI:SS') AS HORAPROCESO 
                    FROM PRDCOMCATMEDLEC.PREDIO 
                    INNER JOIN PRDCOMCATMEDLEC.CLIENT ON (PREDIO.PREREGION = CLIENT.PREREGION) AND (PREDIO.PREZONA = CLIENT.PREZONA) AND (PREDIO.PRESECTOR = CLIENT.PRESECTOR) AND (PREDIO.PREMZN = CLIENT.PREMZN) AND (PREDIO.PRELOTE = CLIENT.PRELOTE) 
                    AND CLIENT.CLICODFAC = ?
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.COAGUA ON (PREDIO.PREREGION = COAGUA.PREREGION) AND (PREDIO.PREZONA = COAGUA.PREZONA) AND (PREDIO.PRESECTOR = COAGUA.PRESECTOR) AND (PREDIO.PREMZN = COAGUA.PREMZN) AND (PREDIO.PRELOTE = COAGUA.PRELOTE) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ZONASEC ON (ZONASEC.PREREGION = PREDIO.PREREGION) AND (ZONASEC.PREZONA = PREDIO.PREZONA) AND (ZONASEC.PRESECTOR = PREDIO.PRESECTOR) AND (ZONASEC.PRELOCALI = PREDIO.PRELOCALI) 
                    INNER JOIN PRDCOMCATMEDLEC.RLURBA ON (RLURBA.PREREGION = PREDIO.PREREGION) AND (RLURBA.PRELOCALI = PREDIO.PRELOCALI) AND (RLURBA.PREURBA = PREDIO.PREURBA) 
                    INNER JOIN PRDCOMCATMEDLEC.RLCALL ON (RLCALL.PREREGION = PREDIO.PREREGION) AND (RLCALL.PRELOCALI = PREDIO.PRELOCALI) AND (RLCALL.PRECALLE = PREDIO.PRECALLE) 
                    INNER JOIN PRDCOMCATMEDLEC.LOCALI ON (LOCALI.PREREGION = PREDIO.PREREGION) AND (LOCALI.PRELOCALI = PREDIO.PRELOCALI) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.CODESA ON (PREDIO.PREREGION = CODESA.PREREGION) AND (PREDIO.PREZONA = CODESA.PREZONA) AND (PREDIO.PRESECTOR = CODESA.PRESECTOR) AND (PREDIO.PREMZN = CODESA.PREMZN) AND (PREDIO.PRELOTE = CODESA.PRELOTE) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESTPRE ON (ESTPRE.CODESTPRE = PREDIO.CODESTPRE) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MATCON ON (MATCON.CODMATCON = PREDIO.CODMATCON) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MATVER ON (CODMATVER = VDAMATCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.PISCIN ON (PISCIN.PISCINCOD = PREDIO.PISCINCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.PROVIN ON (PROVINCOD = PREPROVIN) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.RESEVO ON (RESEVO.CODTIPRES = PREDIO.CODTIPRES) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TIPINM ON (TIPINM.CODTIPINM = PREDIO.CODTIPINM) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TPAVIM ON (PAVICOD = CLLPAVCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ENTEJE ON (ENTEJE.CONDENTEJX = CODESA.CONDENTEJX) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESCJAG ON (ESCJAG.CAJESTCOD = CODESA.CAJESTCOD) AND (ESCJAG.CAJESTCOD = COAGUA.CAJESTCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MEDIDO ON (MEDIDO.MEDCODIGO = COAGUA.MEDCODIGO) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.DICOAGMED ON (DICOAGMED.DIAMEDCOD = MEDIDO.DIAMEDCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESMEDI ON (ESMEDI.MEDESTCOD = MEDIDO.MEDESTCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TIPMED ON (TIPMED.MEDTIPCODX = MEDIDO.MEDTIPCODX)
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TMEDCONDICION ON (TMEDCONDICION.MEDCONCOD = MEDIDO.MEDCONCOD)
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MMEDIDORFAB ON (MMEDIDORFAB.MEDCODYGO = MEDIDO.MEDCODYGO)
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TMARMED ON (TMARMED.MAMCOD = MMEDIDORFAB.MAMCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TMARMEDLEVEL1 ON (TMARMEDLEVEL1.MAMCOD = MMEDIDORFAB.MAMCOD) AND (TMARMEDLEVEL1.MOMCOD = MMEDIDORFAB.MOMCOD)
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.DICOAG ON (DICOAG.CONDIACOD = COAGUA.CONDIACOD)
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.EJECCNXAGUA ON (EJECCNXAGUA.CONENTEJX = COAGUA.CONENTEJX) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESTCON ON (ESTCON.CONESTADO = COAGUA.CONESTADO)
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MATCJA ON (MATCJA.CONCAJMAT = COAGUA.CONCAJMAT)
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TBPCJA ON (TBPCJA.AGUTABCOD = COAGUA.AGUTABCOD)
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TBTPST ON (TBTPST.ESTTAPCOD = COAGUA.ESTTAPCOD)
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TMCXAG ON (TMCXAG.CNAMATCOD = COAGUA.CNAMATCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.UBIMED ON (UBIMED.CONUBICAJ = COAGUA.CONUBICAJ) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESTCONDE ON (ESTCONDE.CONDESTAD = CODESA.CONDESTAD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.MATCJADE ON (MATCJADE.CAJMATCOD = CODESA.CAJMATCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TBPCJAD ON (TBPCJAD.DESTAPCOD = CODESA.DESTAPCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TBTPSTDES ON (TBTPSTDES.STDTAPCOD = CODESA.STDTAPCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.UBIMEDDES ON (UBIMEDDES.CONDUBICA = CODESA.CONDUBICA) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.DICODE ON (DICODE.CONDIDCOD = CODESA.CONDIDCOD) 
                    INNER JOIN PRDCOMCATMEDLEC.PROPIE ON (CLIENT.CLICODFAC = PROPIE.CLICODFAC) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.REGLOC ON (REGLOC.PREREGION = PROPIE.PREREGION) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TARIFA ON (TARIFA.CODCATTAR = PROPIE.CODCATTAR) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.ESCLTE ON (ESCLTE.CODESCLTE = CLIENT.CODESCLTE) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TABSAG ON (TABSAG.CODABASAG = CLIENT.CODABASAG) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TABSDE ON (TABSDE.CODABASDE = CLIENT.CODABASDE) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TIPSER ON (TIPSER.CODTIPSER = CLIENT.CODTIPSER) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.TIPTEN ON (TIPTEN.CODTIPTEN = CLIENT.CODTIPTEN) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.USOINM ON (USOINM.INMUSOCOD = CLIENT.INMUSOCOD) 
                    LEFT OUTER JOIN PRDCOMCATMEDLEC.AMBITO ON (AMBITO.AMBCOD = LOCALI.AMBCOD) 
                    ORDER BY PREDIO.PREREGION, PREDIO.PREZONA, PREDIO.PRESECTOR, PREDIO.PREMZN, PREDIO.PRELOTE, CLIENT.CLICODID, CLIENT.CLICODIGO", array($numero));
                }
            } elseif($tipo == 6) {
                $query = $this->oracle->query('SELECT * FROM PRDDBFCOMERCIAL.PSUNAT WHERE RUC = ?', array($numero));
            } else {
                $query = $this->oracle->query('SELECT * FROM PRDDBFCOMERCIAL.DOCIDENT WHERE NRODOC = ? AND TIPDOC = ?', array($numero, $tipo));
            }
            return $query->row_array();
        }

        public function getMedios(){
            $query = $this->oracle->query('SELECT * FROM PRDGESTIONCOMERCIAL.MMODOATE');
            return $query->result_array();
        }

        public function getDepartamento(){
            $this->oracle->select("*");
            $this->oracle->from("PRDGESTIONCOMERCIAL.CUBIGEO");
            return $this->oracle->get()->row_array();
        }

        public function getProvincias(){
            $query = $this->oracle->query('SELECT * FROM PRDGESTIONCOMERCIAL.CUBIGEO1');
            return $query->result_array();
        }

        public function getDistritos($id){
            $query = $this->oracle->query('SELECT * FROM PRDGESTIONCOMERCIAL.CUBIGEO2 WHERE CPVCOD = ?', array($id));
            return $query->result_array();
        }

    }